#pragma once

const int DRIVEBASE_LEFT_SIDE_FOLLOWER_ID = 2;
const int DRIVEBASE_LEFT_SIDE_LEADER_ID = 3;
const int DRIVEBASE_RIGHT_SIDE_FOLLOWER_ID = 4;
const int DRIVEBASE_RIGHT_SIDE_LEADER_ID = 5;

const int JOYSTICK_DRIVER = 0;

const int YAW_CONTROLLER_P = 1;
const int YAW_CONTROLLER_I = 0;
const int YAW_CONTROLLER_D = 0;
const int YAW_CONTROLLER_TOLERANCE = 2;